name: Ornikar Check Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Toutes les heures
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          ORNIKAR_EMAIL: ${{ secrets.ORNIKAR_LOGIN }}
          ORNIKAR_PASSWORD: ${{ secrets.ORNIKAR_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python ornikar_scraper.py
